package com.shiro.classflow.ui.theme

import androidx.compose.ui.graphics.Color

// ── Sakura Pink (默认主题) ──
// Light
val SakuraPrimary = Color(0xFFC2185B)
val SakuraOnPrimary = Color(0xFFFFFFFF)
val SakuraPrimaryContainer = Color(0xFFFFD9E2)
val SakuraOnPrimaryContainer = Color(0xFF3E001D)
val SakuraSecondary = Color(0xFF9C4164)
val SakuraOnSecondary = Color(0xFFFFFFFF)
val SakuraSecondaryContainer = Color(0xFFFFD9E2)
val SakuraOnSecondaryContainer = Color(0xFF3E001D)
val SakuraTertiary = Color(0xFF8B5065)
val SakuraOnTertiary = Color(0xFFFFFFFF)
val SakuraTertiaryContainer = Color(0xFFFFD9E2)
val SakuraOnTertiaryContainer = Color(0xFF3A0722)
val SakuraBackground = Color(0xFFFFF0F3)
val SakuraOnBackground = Color(0xFF2B1520)
val SakuraSurface = Color(0xFFFFF5F7)
val SakuraOnSurface = Color(0xFF2B1520)
val SakuraSurfaceVariant = Color(0xFFF4D8DF)
val SakuraOnSurfaceVariant = Color(0xFF5C3A47)
val SakuraOutline = Color(0xFF9B7585)
val SakuraError = Color(0xFFBA1A1A)
val SakuraOnError = Color(0xFFFFFFFF)
val SakuraErrorContainer = Color(0xFFFFDAD6)
val SakuraOnErrorContainer = Color(0xFF410002)

// Dark
val SakuraPrimaryDark = Color(0xFFFFB1C8)
val SakuraOnPrimaryDark = Color(0xFF650033)
val SakuraPrimaryContainerDark = Color(0xFF8C0D48)
val SakuraOnPrimaryContainerDark = Color(0xFFFFD9E2)
val SakuraSecondaryDark = Color(0xFFEBB1C7)
val SakuraOnSecondaryDark = Color(0xFF4A1531)
val SakuraSecondaryContainerDark = Color(0xFF652B48)
val SakuraOnSecondaryContainerDark = Color(0xFFFFD9E2)
val SakuraTertiaryDark = Color(0xFFE8B0C6)
val SakuraOnTertiaryDark = Color(0xFF45192C)
val SakuraTertiaryContainerDark = Color(0xFF5D3049)
val SakuraOnTertiaryContainerDark = Color(0xFFFFD9E2)
val SakuraBackgroundDark = Color(0xFF221218)
val SakuraOnBackgroundDark = Color(0xFFF2DEE4)
val SakuraSurfaceDark = Color(0xFF28141C)
val SakuraOnSurfaceDark = Color(0xFFF2DEE4)
val SakuraSurfaceVariantDark = Color(0xFF5C3A47)
val SakuraOnSurfaceVariantDark = Color(0xFFDFBDC8)
val SakuraOutlineDark = Color(0xFFB08E9A)
val SakuraErrorDark = Color(0xFFFFB4AB)
val SakuraOnErrorDark = Color(0xFF690005)
val SakuraErrorContainerDark = Color(0xFF93000A)
val SakuraOnErrorContainerDark = Color(0xFFFFDAD6)

// ── Afternoon Blue-Gray (12:00-18:00) ──
// Light
val AfternoonPrimary = Color(0xFF5C7A9E)
val AfternoonOnPrimary = Color(0xFFFFFFFF)
val AfternoonPrimaryContainer = Color(0xFFD8E6F7)
val AfternoonOnPrimaryContainer = Color(0xFF1A2E42)
val AfternoonSecondary = Color(0xFF6B8AA8)
val AfternoonOnSecondary = Color(0xFFFFFFFF)
val AfternoonSecondaryContainer = Color(0xFFD8E6F7)
val AfternoonOnSecondaryContainer = Color(0xFF1A2E42)
val AfternoonTertiary = Color(0xFF7A8FA5)
val AfternoonOnTertiary = Color(0xFFFFFFFF)
val AfternoonTertiaryContainer = Color(0xFFD8E6F7)
val AfternoonOnTertiaryContainer = Color(0xFF1F3448)
val AfternoonBackground = Color(0xFFF0F5FA)
val AfternoonOnBackground = Color(0xFF1A2530)
val AfternoonSurface = Color(0xFFF5F8FC)
val AfternoonOnSurface = Color(0xFF1A2530)
val AfternoonSurfaceVariant = Color(0xFFDDE5EF)
val AfternoonOnSurfaceVariant = Color(0xFF42505E)
val AfternoonOutline = Color(0xFF7A8896)
val AfternoonError = Color(0xFFBA1A1A)
val AfternoonOnError = Color(0xFFFFFFFF)
val AfternoonErrorContainer = Color(0xFFFFDAD6)
val AfternoonOnErrorContainer = Color(0xFF410002)

// Dark
val AfternoonPrimaryDark = Color(0xFFACC7E8)
val AfternoonOnPrimaryDark = Color(0xFF1A3A5C)
val AfternoonPrimaryContainerDark = Color(0xFF3D5A7E)
val AfternoonOnPrimaryContainerDark = Color(0xFFD8E6F7)
val AfternoonSecondaryDark = Color(0xFFB8D0EA)
val AfternoonOnSecondaryDark = Color(0xFF253E58)
val AfternoonSecondaryContainerDark = Color(0xFF3D5570)
val AfternoonOnSecondaryContainerDark = Color(0xFFD8E6F7)
val AfternoonTertiaryDark = Color(0xFFC2D5E8)
val AfternoonOnTertiaryDark = Color(0xFF2A4258)
val AfternoonTertiaryContainerDark = Color(0xFF425970)
val AfternoonOnTertiaryContainerDark = Color(0xFFD8E6F7)
val AfternoonBackgroundDark = Color(0xFF121A24)
val AfternoonOnBackgroundDark = Color(0xFFE2E8F0)
val AfternoonSurfaceDark = Color(0xFF1A2332)
val AfternoonOnSurfaceDark = Color(0xFFE2E8F0)
val AfternoonSurfaceVariantDark = Color(0xFF42505E)
val AfternoonOnSurfaceVariantDark = Color(0xFFC2CDD8)
val AfternoonOutlineDark = Color(0xFF8C98A6)
val AfternoonErrorDark = Color(0xFFFFB4AB)
val AfternoonOnErrorDark = Color(0xFF690005)
val AfternoonErrorContainerDark = Color(0xFF93000A)
val AfternoonOnErrorContainerDark = Color(0xFFFFDAD6)

// ── Evening Lavender (18:00-6:00) ──
// Light
val EveningPrimary = Color(0xFF9B7EBD)
val EveningOnPrimary = Color(0xFFFFFFFF)
val EveningPrimaryContainer = Color(0xFFE8DFF5)
val EveningOnPrimaryContainer = Color(0xFF2E1A42)
val EveningSecondary = Color(0xFFAA8DC4)
val EveningOnSecondary = Color(0xFFFFFFFF)
val EveningSecondaryContainer = Color(0xFFE8DFF5)
val EveningOnSecondaryContainer = Color(0xFF2E1A42)
val EveningTertiary = Color(0xFFB598C8)
val EveningOnTertiary = Color(0xFFFFFFFF)
val EveningTertiaryContainer = Color(0xFFE8DFF5)
val EveningOnTertiaryContainer = Color(0xFF331F45)
val EveningBackground = Color(0xFFF5F0FA)
val EveningOnBackground = Color(0xFF281A35)
val EveningSurface = Color(0xFFF8F5FC)
val EveningOnSurface = Color(0xFF281A35)
val EveningSurfaceVariant = Color(0xFFE5DDEF)
val EveningOnSurfaceVariant = Color(0xFF4A3E5C)
val EveningOutline = Color(0xFF8A7A9B)
val EveningError = Color(0xFFBA1A1A)
val EveningOnError = Color(0xFFFFFFFF)
val EveningErrorContainer = Color(0xFFFFDAD6)
val EveningOnErrorContainer = Color(0xFF410002)

// Dark
val EveningPrimaryDark = Color(0xFFD0B8E8)
val EveningOnPrimaryDark = Color(0xFF3A1A5C)
val EveningPrimaryContainerDark = Color(0xFF5D3E7E)
val EveningOnPrimaryContainerDark = Color(0xFFE8DFF5)
val EveningSecondaryDark = Color(0xFFDCC5EA)
val EveningOnSecondaryDark = Color(0xFF402558)
val EveningSecondaryContainerDark = Color(0xFF583D70)
val EveningOnSecondaryContainerDark = Color(0xFFE8DFF5)
val EveningTertiaryDark = Color(0xFFE2CCE8)
val EveningOnTertiaryDark = Color(0xFF452A58)
val EveningTertiaryContainerDark = Color(0xFF5D4270)
val EveningOnTertiaryContainerDark = Color(0xFFE8DFF5)
val EveningBackgroundDark = Color(0xFF1A1224)
val EveningOnBackgroundDark = Color(0xFFECE2F0)
val EveningSurfaceDark = Color(0xFF231A32)
val EveningOnSurfaceDark = Color(0xFFECE2F0)
val EveningSurfaceVariantDark = Color(0xFF4A3E5C)
val EveningOnSurfaceVariantDark = Color(0xFFCEC2D8)
val EveningOutlineDark = Color(0xFF9E8CA6)
val EveningErrorDark = Color(0xFFFFB4AB)
val EveningOnErrorDark = Color(0xFF690005)
val EveningErrorContainerDark = Color(0xFF93000A)
val EveningOnErrorContainerDark = Color(0xFFFFDAD6)
